name: tag_reader
description: "A tag reader for mp3 (id3) and mp4/m4a/m4b."
version: 1.0.0

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  charset: ^2.0.1
  collection: ^1.18.0
  intl: ^0.20.2
  logging: ^1.2.0
  meta: ^1.11.0
  path: ^1.9.0
  xml: ^6.5.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
